all:
	pdflatex relatorio-POO-CamposinhosOliveiraSantos.tex
	bibtex relatorio-POO-CamposinhosOliveiraSantos
	pdflatex relatorio-POO-CamposinhosOliveiraSantos
	pdflatex relatorio-POO-CamposinhosOliveiraSantos

clean:

	rm *.aux *.log *.out *.toc *.bbl *.blg *~ *xml *backup *blx*

